sudo: false
language: rust

cache:
  - cargo

install:
  - "script/bootstrap"
  
script:
  - "script/cibuild"

after_script:
  - "script/after_cibuild"

rust:
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - texinfo
      - graphviz

notifications:
  email:
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#xtensis-editor"
    nick: xtensis-ci
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: false
