[package]
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
description = "Extendable editing: ignore the rules."
homepage = "https://github.com/xtensis-editor/xtensis-core"
keywords = ["editor", "framework", "text"]
license = "GPL-3.0"
name = "xtensis-core"
readme = "README.md"
repository = "https://github.com/xtensis-editor/xtensis-core.git"
version = "0.1.0"

[lib]
name = "xtensis"
path = "src/lib.rs"

[[bin]]
name = "xtc"
path = "src/bin/xtc.rs"

[features]
default= []

[dependencies]
gapbuffer= "0.1.1"
log = "0.3.6"
serde = "0.9.11"
serde_json = "0.9.9"
serde_derive = "0.9.11"
slog = "1.3.2"
slog-json = "1.2.1"
slog-term = "1.3.3"
slog-scope = "*"
time = "0.1.35"

[dependencies.clippy]
version = "0.0.121"
optional = true

[dependencies.uuid]
version = "0.3.1"
features = ["v4"]

[dependencies.clap]
version = "2"
features = ["suggestions", "color", "wrap_help"]
