[package]
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
description = "Extendable editing: ignore the rules."
homepage = "https://github.com/xtensis-editor/xtensis-core"
keywords = ["editor", "framework", "text"]
license = "GPL-3.0"
name = "xtensis-core"
readme = "README.md"
repository = "https://github.com/xtensis-editor/xtensis-core.git"
version = "0.1.0"

[lib]
name = "xtensis_core"
path = "src/lib.rs"

[[bin]]
name = "xtc"
path = "src/bin/xtc.rs"

[features]
default= []

[dependencies]
gapbuffer= "0.1.1"
log = "0.3.7"
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
slog = "2.0.0-3"
slog-json = "~2.0.0-4"
slog-term = "~2.0.0-4"
slog-async = "*"
time = "0.1.36"

[dependencies.clippy]
version = "0.0.125"
optional = true

[dependencies.uuid]
version = "0.5.0"
features = ["v4"]

[dependencies.clap]
version = "2.23.3"
features = ["suggestions", "color", "wrap_help"]
