[package]
name = "xt-remote-daemon"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[[bin]]
name = "xtrd"

[dependencies]
slog = "2.7.0"
slog-async = "2.6.0"
slog-term = "2.8.0"

[dependencies.clap]
features = [
    "suggestions",
    "color",
    "wrap_help"
]
version = "2.33.3"
